spring:
  profiles:
    active: develop
  jpa:
    open-in-view: false
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    initialize: false
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password
    virtual-host: dev

server:
  port: 8090

stripe.simulator.charges-uri: https://sandbox.playtomic.io/v1/stripe-simulator/charges
stripe.simulator.refunds-uri: https://sandbox.playtomic.io/v1/stripe-simulator/payments/{payment_id}/refunds
